spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  application:
    name: demo-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080
  servlet: 
    context-path: /emp/api
